parameters:
#   Get your free API access http://en.business.skyscanner.net/en-gb/products/travel-apis/
#   Create a free account at https://postmarkapp.com/ for sending e-mails
#   Create a free account at https://slack.com/ to send you a private message right away!
    jeancsil.flightspy.api.key: 'API_KEY'
    jeancsil.flightspy.email.api.key: 'YOUR_POSTMARK_API_KEY'
    jeancsil.flightspy.api.host: 'http://partners.api.skyscanner.net'
    jeancsil.flightspy.slack.webhook.url: 'https://hooks.slack.com/services/xxx/xxx/xxx'
    jeancsil.flightspy.slack.username: 'yourSlackUsernameWithoutTheAt'

    jeancsil.flightspy.email.config.from: 'me@mycompany.com'
    jeancsil.flightspy.email.config.to: 'your@company.com'
    jeancsil.flightspy.email.config.subject: 'The best deal!'
    jeancsil.flightspy.email.config.html: '<html><body>This is the html template<br />{message}</body></html>'

    jeancsil.flightspy.http.client.config:
        base_uri: '%jeancsil.flightspy.api.host%'
        timeout: 10
        headers:
            Content-Type: 'application/x-www-form-urlencoded'
            Accept: 'application/json'
            User-Agent: 'Mozilla/4.0 (Windows NT 9.0; WOW64)'

    jeancsil.flightspy.elasticsearch.host: elasticsearch
    jeancsil.flightspy.elasticsearch.port: 9200
    jeancsil.flightspy.elasticsearch.indexName: flightspy
    jeancsil.flightspy.elasticsearch.historyType: history
    jeancsil.flightspy.elasticsearch.notificationType: notification